### ISSUE TITLE
consuming laravel-face-detection

### ISSUE THREAD

**Issue by wahbalaamri** [freearhey/laravel-face-detection#5]
F:\laravel\example-app> composer require freearhey/laravel-face-detection
Using version ^1.3 for freearhey/laravel-face-detection
./composer.json has been updated
Running composer update freearhey/laravel-face-detection
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires freearhey/laravel-face-detection ^1.3 -> satisfiable by freearhey/laravel-face-detection[1.3.0].
    - freearhey/laravel-face-detection 1.3.0 requires illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by freearhey** [comment]
Could you specify the version of Laravel?

**Comment by wahbalaamri** [comment]
laravel 8

**Comment by freearhey** [comment]
I can't reproduce the error. If you install `laravel:^8.0` from scratch (https://laravel.com/docs/8.x/installation#installation-via-composer) and try to put `laravel-face-detection` on top of it, it works fine. 

So I assume that the problem is with the version of one of your dependencies, such as `illuminate/support`, which is mentioned in the log, or some other. That's all that comes to mind.
